In [1]:
import utils

In [2]:
print(utils.get_film_year_release('The Empire Strikes Back'))
print(get_film_year_release ())

TypeError: get_film_year_release() takes 0 positional arguments but 1 was given

In [4]:
utils.sales_total_revenue ()
utils.sales_revenue_by_rep ('brandonwolf@example.com')
utils.poseters_sold_by_rep ('brandonwolf@example.com')
utils.get_most_used_promo_code ( )
utils.get_most_used_promo_code ( )
utils.poster_qty_sold_by_rep ('brandonwolf@example.com')
utils.get_most_sold_poster_content ( )
utils.get_top10_salesrep_by_poster_qty ( )
utils.get_top10_salesrep_by_revenue  ( )
utils.get_top10_posters_by_revenue  ( )
utils.get_top10_posters_by_sales_qty  ( )
utils.get_top10_promo_code_by_sales  ( )
utils.get_promo_code_and_sales_qty  ( )
utils.get_promo_code_and_revenue  ( )
utils.get_order_most_appearing_starship () 
utils.get_order_film_by_most_used_starship ( )
utils.get_all_starships_appear_in_a_movie  ('Attack of the Clones')
utils.get_all_films_starship_appear ('Millennium Falcon')
utils.get_polupar_films_ordered_by_posters_sold ( )

                 film_name  total_quantity
0      Revenge of the Sith          194227
1       Return of the Jedi          180169
2     Attack of the Clones          165072
3  The Empire Strikes Back          140748
4               A New Hope          133069
5       The Phantom Menace           89230

In [5]:
print(utils.sales_total_revenue ())
print(utils.sales_revenue_by_rep ('brandonwolf@example.com'))
print(utils.poseters_sold_by_rep ('brandonwolf@example.com'))
print(utils.get_most_used_promo_code ( ))
print(utils.get_most_used_promo_code ( ))
print(utils.poster_qty_sold_by_rep ('brandonwolf@example.com'))
print(utils.get_most_sold_poster_content ( ))
print(utils.get_top10_salesrep_by_poster_qty ( ))
print(utils.get_top10_salesrep_by_revenue  ( ))
print(utils.get_top10_posters_by_revenue  ( ))
print(utils.get_top10_posters_by_sales_qty  ( ))
print(utils.get_top10_promo_code_by_sales  ( ))
print(utils.get_promo_code_and_sales_qty  ( ))
print(utils.get_promo_code_and_revenue  ( ))
print(utils.get_order_most_appearing_starship ()) 
print(utils.get_order_film_by_most_used_starship ( ))
print(utils.get_all_starships_appear_in_a_movie  ('Attack of the Clones'))
print(utils.get_all_films_starship_appear ('Millennium Falcon'))
print(utils.get_polupar_films_ordered_by_posters_sold ( ))

   total_revenue
0     29259908.0
   revenue
0    850.0
             poster_content
0  AA-9 Coruscant freighter
   promo_code
0  youtube ad
   promo_code
0  youtube ad
   total_qty
0         12
                 poster_content  total_qty
0  Sentinel-class landing craft      25850
                       sales_rep  total_qty
0             vsmith@example.com       2219
1              sdunn@example.com       1992
2         lewisbryan@example.com       1986
3  rodriguezjennifer@example.org       1964
4          krystal99@example.com       1958
5             noah48@example.org       1952
6        jamesbrewer@example.org       1942
7          cooperamy@example.com       1940
8            mkeller@example.com       1936
9             erin97@example.net       1936
                 sales_rep  total_revenue
0        sdunn@example.com       194539.0
1   flemingamy@example.org       179361.0
2       aprice@example.com       167843.0
3  jamesbrewer@example.org       163905.0
4       toni73@example.org       158695.0
5       erin97@example.net       156584.0
6    rebecca61@example.com       154877.0
7   ryanhudson@example.com       148689.0
8       noah48@example.org       147844.0
9      dpatton@example.com       140080.0
                 poster_content  total_revenue
0                       Slave 1      1457225.0
1              Jedi starfighter      1237660.0
2       J-type diplomatic barge      1125099.0
3                        Y-wing      1055778.0
4              Naboo star skiff      1039404.0
5       Republic attack cruiser      1002090.0
6          Naboo Royal Starship       983129.0
7  Sentinel-class landing craft       966588.0
8                       arc-170       960954.0
9         Republic Assault ship       951035.0
                 poster_content  total_qty
0  Sentinel-class landing craft      25850
1                       Slave 1      25799
2              Naboo star skiff      24081
3                        Y-wing      22066
4              Jedi starfighter      20969
5       J-type diplomatic barge      20724
6          Naboo Royal Starship      20278
7                 Naboo fighter      19283
8         Republic Assault ship      18856
9                        B-wing      18792
                           promo_code  total_count
0                          youtube ad           81
1                          X link add           73
2             Exclusive social offers           70
3             Newsletter signup offer           70
4                 Free shipping codes           70
5  Discount codes for online shopping           69
6           Flash sale discount codes           68
7                               TV ad           66
8              Holiday-specific codes           65
9                      Referral codes           63
                            promo_code  total_qty
0                           X link add      37479
1                                TV ad      36249
2               Holiday-specific codes      36005
3                           youtube ad      35781
4          Abandoned cart coupon codes      34309
5              Newsletter signup offer      33580
6              Exclusive social offers      32652
7                  Free shipping codes      32503
8                       Referral codes      31710
9                                Radio      30875
10           Flash sale discount codes      30085
11                    Bundle discounts      28645
12               Loyalty program deals      27918
13  Discount codes for online shopping      27596
14                Influencer discounts      26668
15                         Facdbook Ad      26409
16            First purchase discounts      25701
17     Minimum purchase discount codes      22509
18                 Launch coupon codes      22298
19        Offers for purchasing online      20680
                            promo_code  total_revenue
0          Abandoned cart coupon codes      1837455.0
1                           X link add      1740292.0
2               Holiday-specific codes      1686837.0
3                     Bundle discounts      1653407.0
4                                TV ad      1640923.0
5              Newsletter signup offer      1631121.0
6              Exclusive social offers      1575830.0
7                           youtube ad      1542650.0
8                 Influencer discounts      1517277.0
9   Discount codes for online shopping      1491278.0
10                 Free shipping codes      1484209.0
11                      Referral codes      1479651.0
12            First purchase discounts      1478412.0
13           Flash sale discount codes      1436330.0
14                               Radio      1384983.0
15               Loyalty program deals      1335544.0
16     Minimum purchase discount codes      1205352.0
17                         Facdbook Ad      1169397.0
18        Offers for purchasing online      1100489.0
19                 Launch coupon codes       868470.0
                    starship_name  film_name
0                   CR90 corvette          3
1                          Y-wing          3
2                          X-wing          3
3                  Star Destroyer          3
4               Millennium Falcon          3
5              Droid control ship          3
6                   Naboo fighter          2
7   EF76 Nebulon-B escort frigate          2
8                        Executor          2
9                Imperial shuttle          2
10               Jedi starfighter          2
11                Rebel transport          2
12                        Slave 1          2
13       Trade Federation cruiser          1
14               Jedi Interceptor          1
15                         V-wing          1
16        J-type diplomatic barge          1
17       Belbullab-22 starfighter          1
18       AA-9 Coruscant freighter          1
19           Naboo Royal Starship          1
20               Naboo star skiff          1
21                         A-wing          1
22          Republic Assault ship          1
23        Republic attack cruiser          1
24               Republic Cruiser          1
25                       Scimitar          1
26   Sentinel-class landing craft          1
27                        arc-170          1
28                   Solar Sailer          1
29            Banking clan frigte          1
30               Calamari Cruiser          1
31                     Death Star          1
32                         B-wing          1
33       Theta-class T-2c shuttle          1
34                TIE Advanced x1          1
35            H-type Nubian yacht          1
Error: (psycopg2.OperationalError) connection to server at "pg-20d77a1a-samplesource.e.aivencloud.com" (159.89.49.226), port 26689 failed: FATAL:  remaining connection slots are reserved for roles with the SUPERUSER attribute

(Background on this error at: https://sqlalche.me/e/20/e3q8)
None
              starship_name
0                   Slave 1
1        Droid control ship
2             Naboo fighter
3   J-type diplomatic barge
4  AA-9 Coruscant freighter
5          Jedi starfighter
6       H-type Nubian yacht
7     Republic Assault ship
8              Solar Sailer
                 film_name
0               A New Hope
1  The Empire Strikes Back
2       Return of the Jedi
                 film_name  total_quantity
0      Revenge of the Sith          194227
1       Return of the Jedi          180169
2     Attack of the Clones          165072
3  The Empire Strikes Back          140748
4               A New Hope          133069
5       The Phantom Menace           89230

In [6]:
print(utils.get_all_starships_appear_in_a_movie  ('Attack of the Clones'))

              starship_name
0                   Slave 1
1        Droid control ship
2             Naboo fighter
3   J-type diplomatic barge
4  AA-9 Coruscant freighter
5          Jedi starfighter
6       H-type Nubian yacht
7     Republic Assault ship
8              Solar Sailer

In [7]:

print(utils.get_top10_promo_code_by_sales  ( ))

                           promo_code  total_count
0                          youtube ad           81
1                          X link add           73
2             Exclusive social offers           70
3             Newsletter signup offer           70
4                 Free shipping codes           70
5  Discount codes for online shopping           69
6           Flash sale discount codes           68
7                               TV ad           66
8              Holiday-specific codes           65
9                      Referral codes           63
Error: (psycopg2.OperationalError) connection to server at "pg-20d77a1a-samplesource.e.aivencloud.com" (159.89.49.226), port 26689 failed: FATAL:  remaining connection slots are reserved for roles with the SUPERUSER attribute

(Background on this error at: https://sqlalche.me/e/20/e3q8)
None
Error: (psycopg2.OperationalError) connection to server at "pg-20d77a1a-samplesource.e.aivencloud.com" (159.89.49.226), port 26689 failed: FATAL:  remaining connection slots are reserved for roles with the SUPERUSER attribute

(Background on this error at: https://sqlalche.me/e/20/e3q8)
None
Error: (psycopg2.OperationalError) connection to server at "pg-20d77a1a-samplesource.e.aivencloud.com" (159.89.49.226), port 26689 failed: FATAL:  remaining connection slots are reserved for roles with the SUPERUSER attribute

(Background on this error at: https://sqlalche.me/e/20/e3q8)
None
                 film_name  starship_count
0       Return of the Jedi              12
1      Revenge of the Sith              12
2     Attack of the Clones               9
3  The Empire Strikes Back               9
4               A New Hope               8
5       The Phantom Menace               5

In [8]:
print(utils.get_promo_code_and_sales_qty  ( ))
print(utils.get_promo_code_and_revenue  ( ))
print(utils.get_order_most_appearing_starship ()) 
print(utils.get_order_film_by_most_used_starship ( ))

                            promo_code  total_qty
0                           X link add      37479
1                                TV ad      36249
2               Holiday-specific codes      36005
3                           youtube ad      35781
4          Abandoned cart coupon codes      34309
5              Newsletter signup offer      33580
6              Exclusive social offers      32652
7                  Free shipping codes      32503
8                       Referral codes      31710
9                                Radio      30875
10           Flash sale discount codes      30085
11                    Bundle discounts      28645
12               Loyalty program deals      27918
13  Discount codes for online shopping      27596
14                Influencer discounts      26668
15                         Facdbook Ad      26409
16            First purchase discounts      25701
17     Minimum purchase discount codes      22509
18                 Launch coupon codes      22298
19        Offers for purchasing online      20680
                            promo_code  total_revenue
0          Abandoned cart coupon codes      1837455.0
1                           X link add      1740292.0
2               Holiday-specific codes      1686837.0
3                     Bundle discounts      1653407.0
4                                TV ad      1640923.0
5              Newsletter signup offer      1631121.0
6              Exclusive social offers      1575830.0
7                           youtube ad      1542650.0
8                 Influencer discounts      1517277.0
9   Discount codes for online shopping      1491278.0
10                 Free shipping codes      1484209.0
11                      Referral codes      1479651.0
12            First purchase discounts      1478412.0
13           Flash sale discount codes      1436330.0
14                               Radio      1384983.0
15               Loyalty program deals      1335544.0
16     Minimum purchase discount codes      1205352.0
17                         Facdbook Ad      1169397.0
18        Offers for purchasing online      1100489.0
19                 Launch coupon codes       868470.0
                    starship_name  film_name
0                   CR90 corvette          3
1                          Y-wing          3
2                          X-wing          3
3                  Star Destroyer          3
4               Millennium Falcon          3
5              Droid control ship          3
6                   Naboo fighter          2
7   EF76 Nebulon-B escort frigate          2
8                        Executor          2
9                Imperial shuttle          2
10               Jedi starfighter          2
11                Rebel transport          2
12                        Slave 1          2
13       Trade Federation cruiser          1
14               Jedi Interceptor          1
15                         V-wing          1
16        J-type diplomatic barge          1
17       Belbullab-22 starfighter          1
18       AA-9 Coruscant freighter          1
19           Naboo Royal Starship          1
20               Naboo star skiff          1
21                         A-wing          1
22          Republic Assault ship          1
23        Republic attack cruiser          1
24               Republic Cruiser          1
25                       Scimitar          1
26   Sentinel-class landing craft          1
27                        arc-170          1
28                   Solar Sailer          1
29            Banking clan frigte          1
30               Calamari Cruiser          1
31                     Death Star          1
32                         B-wing          1
33       Theta-class T-2c shuttle          1
34                TIE Advanced x1          1
35            H-type Nubian yacht          1
Error: (psycopg2.OperationalError) connection to server at "pg-20d77a1a-samplesource.e.aivencloud.com" (159.89.49.226), port 26689 failed: FATAL:  remaining connection slots are reserved for roles with the SUPERUSER attribute

(Background on this error at: https://sqlalche.me/e/20/e3q8)
None

In [11]:
print(utils.get_order_film_by_most_used_starship ( ))

                 film_name  starship_count
0       Return of the Jedi              12
1      Revenge of the Sith              12
2     Attack of the Clones               9
3  The Empire Strikes Back               9
4               A New Hope               8
5       The Phantom Menace               5